const FETCH_DATA_LOADING = "FETCH_DATA_LOADING";
const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";

export {FETCH_DATA_LOADING,FETCH_DATA_SUCCESS,FETCH_DATA_ERROR};
